name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        zig-version: [master]
        os: [ubuntu-latest]
        target:
          - x86_64-linux-gnu
          - x86_64-linux-musl
          - aarch64-linux-gnu
          - aarch64-linux-musl
          - x86_64-freebsd-none
          - aarch64-freebsd-none
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Check Formatting
        run: zig fmt --ast-check --check .

      - name: Build
        run: zig build -Dtarget=${{ matrix.target }} --summary all
